### PR TITLE
Upgrade visualstudiotestagents2015 to "update 3"

### PR DESCRIPTION
**Pull request by JorritSalverda**
The newer version of the tests agent supports parallel execution.

### CODE REVIEW

**Comment by DarwinJS** [comment]
Excellent - will take a look at this very soon and get it worked in!

**Comment by DarwinJS** [comment]
@JorritSalverda - were you able to successfully test a .nupkg built with your changes?

**Comment by JorritSalverda** [comment]
Haven't tried to build the .nupkg yet. I'll will try to do so as soon as I have time for it. Does it fail on your end?

**Comment by DarwinJS** [comment]
@JorritSalverda - Generally I would expect any pull requests to be against code the author has tested - that way I am not finding small syntax errors and hopefully the resultant software install is checked out as well to ensure that the installer automation itself has not also changed behaviors with the new version.  (just like regular software, installers sometimes undergo surprising levels of change in a "small point release")

Could you please compile and test the package locally to see if you get the install you are looking for?

Also pull requests are generally done against a git branch - If you haven't gotten into branches yet I can take this one against master.

**Pull request merged**
