### PR TITLE
Updated to Win32-OpenSSH 2016.05.30.

### PR DESCRIPTION
**Pull request by pivotal-jbarrett**
Also fixed the installer to update the sshd_config with the correct target path.

### CODE REVIEW

**Comment by DarwinJS** [comment]
@pivotal-jbarrett - somehow this pull request is showing all the files as new - can't actually isolate the changes.  Am I missing something?

**Comment by pivotal-jbarrett** [comment]
Maybe I did this wrong but it appeared to me that you were making each version of the package a separate directory. I created a 2016.05.30 directory for this update.

**Comment by DarwinJS** [comment]
Ah yes, you are correct.  I had missed the announcement.  I generally would rather have a note to me that there is a new version out because I always assess the installation document to see if there were any significant changes - for 5_15 there were some pretty extensive changes required.

The new version is packaged - actually did it before coming back to this thread and realizing you were doing the latest release.

**Comment by pivotal-jbarrett** [comment]
Ok, I won't feel bad if you reject my pull and do it yourself. I had to do the work anyway to test some automation for an internal project. 5_30 fixes some issues with profile directories. 

I also took your mates changes to fix permissions issues on Win 2008 R2 thinking they had been fixed but I am seeing now that they don't appear to be, at least when running the installer via WinRM. I will try over RDP next to verify.

**Comment by DarwinJS** [comment]
WinRM and System account are contexts that you have to engineer each package for.  I had to avoid imdisk for opening ISOs because it does not work over remoting (Packer).

Public Chocolatey packages are not tested with WinRM nor System account context (chef client as a service) - so any creative methods they employ may not work.

Psexec might give some grief under these contexts - not sure.

**Pull request closed without merging**
