### PR TITLE
(artifactory-pro) Updated to version 6.5.13

### PR DESCRIPTION
**Pull request by gep13**

### CODE REVIEW

**Comment by DarwinJS** [comment]
Gary,
My testing is failing.
It looks like despite my code to cleanup the cruft that Artifactory install puts in the service registry key, some is slipping through.

Here is the clean up code: https://github.com/DarwinJS/ChocoPackages/blob/master/artifactory-oss/tools/chocolateyinstall.ps1#L81-L87

But in this version it is still generating this cruft:
image

This is not any change that you made, but the non-standard way that this installer manipulates this key.

Are you not seeing the same problem?

Are you able to help with trying to fix this if you can reproduce it?

This fragility is most likely why I'm not so quick to update this package.

**Comment by DarwinJS** [comment]
FYI - I already checked that the LF and file type of their installation bat file are correct.

**Comment by gep13** [comment]
@DarwinJS I never inspected the Registry after the initial installation, I simply installed it, and checked to see if it was working, i.e. opening the site and starting to configure some things.  All of that seemed like it was working, so I never dug into it any further.

I will take another look and see what I can find.

**Comment by DarwinJS** [comment]
FYI - I tested on Windows 10.

**Comment by gep13** [comment]
@darwinjs I tested on Windows Server 2016. Just to confirm, are you saying that after the installation on Windows 10, Artifactory didn’t work for you, or that you just happened to notice the additional characters in the registry key?

**Comment by DarwinJS** [comment]
The service does not launch.  If you remove the cruft manually - and try to launch it works fine.
The code I embedded is how I got around this last time - not sure why it stopped working for this new package.

**Comment by DarwinJS** [comment]
Interesting - this only happens when chocolatey is kicked off from powershell core (6.1.1).  When I be sure to launch the chocolatey package from Windows PowerShell it works fine.

Will push it now.

**Comment by gep13** [comment]
Oh, that is VERY strange!  And it confirms what I am seeing, as I wasn't on PowerShell Core when I did this test.

Thanks for investigating!

**Comment by gep13** [comment]
>@DarwinJS said...
Will push it now.

Let me know when you have done this, and I will take a look at the moderation queue.

**Pull request merged**
